### ISSUE TITLE
Synaptic touch driver

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [calebccff/pmos-oneplus6#1] opened 2021-03-31 08:08 UTC
I noticed that libinput reports the touchscreen being a Synaptics S3706B but from my research it appears it is actually the Synaptics S3320.

Refereneces:
Oneplus 6 http://www.deviceinfohw.ru/devices/item.php?item=151132
Oneplus 6T http://www.deviceinfohw.ru/devices/item.php?item=142394
The S3302 is used on the 6 and 6T plus a bunch of other Oneplus phones: 2, 3, 3T, 5, 5T

Oneplus seem to only use the S3706 on the Oneplus 7 Line of phones
Oneplus 7 http://www.deviceinfohw.ru/devices/item.php?item=51420

I am not sure if the information on the deviceinfohw site is correct or if the difference matters. I found it because there is a problem with the touchscreen with Gnome40 (now in the testing repo) and I wonder if this could have some effect.

PS. Thank you very much for you work on these phones. I bought a 6T just to play with Postmarket, the idea of a mainline phone this powerful is what dreams are made of.

**Comment by kcxt** [comment] 2021-04-01 20:04
Hey, that's quite an interesting find. I've noticed that sometimes when turning on the display it can take quite some time for the touch screen to start working, I'm not exactly sure why this is but I suspect it's just the TS taking some time to wake up.

Dmesg confirms this:
```
[    5.166483] rmi4_f01 rmi4-00.fn01: found RMI device, manufacturer: Synaptics, product: S3706B, fw id: 2827775
[    5.185231] input: Synaptics S3706B as /devices/rmi4-00/input/input2
```

There are potentially several explanation here:

* OnePlus reused the same driver for the OnePlus 6 as previous phones, what the mainline drivers reports is actually correct, and the S3320 driver used downstream only has that name for legacy reasons
* The mainline (RMI4) driver reports the wrong model.

I would be more inclined to trust the upstream driver, however I suspect the best option would be to locate some datasheet and manually verifying these claims.

I don't suspect that this issue would affect Gnome 40, I've used quite a few varied DEs on the device, they do not care what model your touch screen is, it either reports touches as intended, or it does not. In this case it does, I see no reason why that would change on Gnome 40.

I'll close this as there doesn't seem to be any issue here.

**Closed as completed by kcxt** 2021-04-01 20:04 UTC
